### PR TITLE
Updated README to Previous TOC format

### PR DESCRIPTION
**Pull request by mahirk**
Updated the README file to the previous Table of Contents format
Added Code of Conduct to the TOC.

### CODE REVIEW

**Comment by frankcash** [comment]
I guess I'd like to open up a conversation about reverting.  @bryangarza @mrcoven94 please comment.

**Comment by mrcoven94** [comment]
lets try it in a table?
Hackathons | Scholarships | Frontend | Backend | Mobile | General Programming ?
Thoughts? Tables are pretty lol. 
@mahirk @frankcash

**Comment by frankcash** [comment]
:+1:

**Comment by mrcoven94** [comment]
check it out

**Comment by frankcash** [comment]
:+1:

**Comment by mrcoven94** [comment]
The only thing is that keeping the markdown pretty on the editing side sucks balls.

**Comment by frankcash** [comment]
Yeah true, we could just not accept PRs unless they update the README for their added content. 

This PR is invalid as of: 9bcba33c11bcd30380548714bd3ea5ca74e08b24

**Comment by bryangarza** [comment]
What about splitting the repo into multiple more focused repos? For example
one for backend, one for frontend, one for mobile, one for non-code? just a
suggestion.

**Comment by kritinvij** [comment]
well, then it wont be HackerCollective anymore..
We want it to be 1 repo.

​_Kritin Vij_​
University of Washington
Computer Science | Math Minor
*kritinvij@gmail.com kritinvij@gmail.com | *
http://in.linkedin.com/pub/kritin-vij/2b/176/ab0/

**Comment by mrcoven94** [comment]
I like the idea of only having to go to one spot to see everything. Thoughts?

**Comment by frankcash** [comment]
The group is collective but the repo doesn't have to be I guess

**Comment by mrcoven94** [comment]
hmmm... Do we want to end up turning this into a website?

**Comment by frankcash** [comment]
I know angularjs

**Comment by mahirk** [comment]
That sounds like a good idea

**Comment by bryangarza** [comment]
why don't we just use the markdown with github pages?

**Comment by mrcoven94** [comment]
Fuckin AWESOME! I own the domain, code-central , the initial idea was pretty much this.

**Comment by frankcash** [comment]
We could use a Wikia too, that might be easier?

**Comment by mahirk** [comment]
One repo makes more sense, it in itself needs to be more organized, then
the markdowns for the pages easily

**Comment by mahirk** [comment]
Lets move this to an issue? rather than a closed pull request?

**Comment by mrcoven94** [comment]
Lets move it to an issue, and yes, we do need to get it way more organized. Here is the url I have from my start up, that we can use. code-central.co , currently hosted under engx.co/codecentral

**Comment by frankcash** [comment]
I own `hackerqueue.io`  we could use that and I could give some people ssh access to the server it is hosted on?

**Comment by frankcash** [comment]
Best closed PR ever.

**Comment by mrcoven94** [comment]
I like the .io, and especially b/c its a lot more than just code. Leggo.

**Pull request closed without merging**
