### PR TITLE
Update edu.md

### PR DESCRIPTION
**Pull request by shampliu**

### CODE REVIEW

**Comment by frankcash** [comment]
That website appears to cost money to become a member, can you link me to their education discount resource?

**Comment by shampliu** [comment]
I can't seem to find a link to that but if you click Log In, on the right side there should be a panel asking you to "Log in through your organization or school"

**Comment by frankcash** [comment]
Does doing such waive the fee?

**Comment by shampliu** [comment]
Yes, its free for students

**Comment by mahirk** [comment]
@shampliu could you provide a description for your next pull request?

**Comment by frankcash** [comment]
Closing this.

**Pull request closed without merging**
