### PR TITLE
Fixed broken links

### PR DESCRIPTION
**Pull request by mohnjoosemiller**
All links should direct to a relevant page, though some seem to be missing pages as of now.

Let me know if I missed something.

### CODE REVIEW

**Comment by frankcash** [comment]
:love_hotel:

**Comment by mohnjoosemiller** [comment]
:heart_eyes:

**Comment by bryangarza** [comment]
:hamster: :hear_no_evil: :heart_eyes: :lock:

**Comment by mohnjoosemiller** [comment]
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<3333333333333333333333333

**Pull request merged**
